version: '3.8'

services:
  backend:
    build: ./backend-flask
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
    volumes:
      - ./backend-flask:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    build: ./frontend-express
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:5000
      - NODE_ENV=development
    depends_on:
      - backend
    volumes:
      - ./frontend-express:/app
      - /app/node_modules
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    restart: unless-stopped

networks:
  default:
    driver: bridge
